In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
label_path = '/Users/ShiyuMu/Desktop/HTS-demo_NIT-SONG070-F001/data/labels/mono/'
fileList = [label_path + f for f in os.listdir(label_path) if f.endswith('.lab')]

In [99]:
# build dictionary and save to dict file
# phone_dict = set()
# for file in fileList:
#   with open(file, 'r') as f:
#     for line in f:
#       phone_dict.add(line.strip().split()[-1])
# phone_dict
# with open('JPN_phone_dict.txt', 'w') as f:
#   for element in phone_dict:
#     f.write(str(element)+'\n')

In [3]:
# current phone to before-current-next file and save as csv file 
try:
  # create dictionary to hold all the csv file 
  os.mkdir(label_path + '/csv/');
  print('csv dictionary created')
except:
  pass
for file in fileList:
  df = pd.read_csv(file, sep=" ", header=None)
  df.columns = ["beg", "end", "current"]
  df['before'] = pd.Series(['None']).append(df['current']).reset_index(drop=True)
  df['next'] = df['current'][1:].append(pd.Series(['None'])).reset_index(drop=True)
  df.to_csv(label_path + '/csv/'+ file.split('/')[-1]+'.csv', sep='\t', index=False)

In [4]:
# load the japanese phone dictionary 
def load_phone_dict():
  phone_dict = list()
  with open('JPN_phone_dict.txt', 'r') as f:
    for line in f:
      phone_dict.append(line.strip())
  return phone_dict

In [5]:
def phone_to_one_hot(phone, phone_dict):
  tmp = list(np.zeros(len(phone_dict)))
  if phone=='None':   
    return tmp
  else:
    tmp[phone_dict.index(phone)] = 1.0
    return tmp

In [6]:
# example of loading csv files and get one-hot vectors. 
csv_path = '/Users/ShiyuMu/Desktop/HTS-demo_NIT-SONG070-F001/data/labels/mono/csv/'
csvList = [csv_path + f for f in os.listdir(csv_path) if f.endswith('.csv')]
df_list = list()
## add all csv files to a list
for file in csvList:
  df = pd.read_csv(file, sep='\t')
  df_list.append(df)

In [7]:
# df_list[0].head()
# df_frame_list = list()
# df_frame_list[0]
# df_list[0]

In [9]:
# one csv will look like this
def time_to_frame(time, window_size, step_size):
  number_windows=(time-2*window_size)//step_size
  if number_windows >= 0:
    return number_windows
  else:
    return 0
time_to_frame(42200000, 25000, 10000)

4215

In [50]:
df['beg'].values[5]

36200000

In [10]:
window_size = 25000
step_size = 10000

for df in df_list:
#   print(len(df['beg'].values))
  for index in range(len(df['beg'].values)):
#     print(index)
    df['beg'].values[index] = time_to_frame(df['beg'].values[index], window_size, step_size)
  for index in range(len(df['end'].values)):
#     print(index)
    df['end'].values[index] = time_to_frame(df['end'].values[index], window_size, step_size)

In [16]:
test_df = df_list[0]

In [29]:
test_df

       beg    end current before  next
0        0   2375     pau   None     n
1     2375   2435       n    pau     e
2     2435   3040       e      n     N
3     3040   3575       N      e     n
4     3575   3615       n      N     e
5     3615   4215       e      n     N
6     4215   4975       N      e     k
7     4975   5080       k      N     o
8     5080   5375       o      k     r
9     5375   5460       r      o     o
10    5460   6010       o      r     r
11    6010   6060       r      o     i
12    6060   6660       i      r     y
13    6660   6685       y      i     o
14    6685   7250       o      y   pau
15    7250   7505     pau      o     o
16    7505   7785       o    pau     k
17    7785   7855       k      o     o
18    7855   8175       o      k     o
19    8175   8430       o      o     r
20    8430   8495       r      o     o
21    8495   9035       o      r     r
22    9035   9110       r      o     i
23    9110   9635       i      r     y
24    9635   9660       y      i     o
25    9660  11435       o      y   pau
26   11435  11955     pau      o     b
27   11955  12120       b    pau     o
28   12120  12840       o      b     o
29   12840  13170       o      o     y
..     ...    ...     ...    ...   ...
127  46865  47410       o      m     r
128  47410  47495       r      o     o
129  47495  47955       o      r     t
130  47955  48035       t      o     a
131  48035  49795       a      t   pau
132  49795  50355     pau      a     d
133  50355  50495       d    pau     e
134  50495  51295       e      d     N
135  51295  51615       N      e     d
136  51615  51660       d      N     e
137  51660  52210       e      d     N
138  52210  52540       N      e     N
139  52540  53080       N      N     d
140  53080  53110       d      N     a
141  53110  53425       a      d     i
142  53425  53960       i      a     k
143  53960  54065       k      i     o
144  54065  54565       o      k     n
145  54565  54670       n      o     i
146  54670  55185       i      n   pau
147  55185  55440     pau      i    sh
148  55440  55560      sh    pau     o
149  55560  55880       o     sh     o
150  55880  56395       o      o     n
151  56395  56480       n      o     o
152  56480  57030       o      n     f
153  57030  57140       f      o     u
154  57140  57745       u      f     e
155  57745  59830       e      u   pau
156  59830  62395     pau      e  None

[157 rows x 5 columns]

In [23]:
print(test_df.shape)

(157, 5)

In [32]:
unfold_df = pd.DataFrame()
for index in range(test_df.shape[0]):
  beg_ = test_df.iloc[index]['beg']
  end_ = test_df.iloc[index]['end']
  current_ = test_df.iloc[index]['current']
  before_ = test_df.iloc[index]['before']
  next_ = test_df.iloc[index]['next']
  unfold_df.append([current_, 'None', current_], column=['current', 'before', 'next'])
  for i in range(beg_+1, end):
    unfold_df.append([current_, current_, current_], column=['current', 'before', 'next'])
  unfold_df.append([current_, current_, 'None'], column=['current', 'before', 'next'])

TypeError: list() takes at most 1 argument (3 given)

In [30]:
#### For position coarse vector
# for index in range(test_df.shape[0]):
# #   print(index)
#   beg = test_df.iloc[index]['beg']
#   end = test_df.iloc[index]['end']
#   mid = beg + int((end-beg)/2)
#   print(mid)

In [26]:

for i in range(len(df_list[0]['beg'].values)):
  df_list[0]['beg'][i] = time_to_frame(df_list[0]['beg'].values[i], 25000, 10000)

/Users/ShiyuMu/anaconda/envs/ML/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [27]:
df_list[0]

       beg        end current before  next
0       -5   23800000     pau   None     n
1     2375   24400000       n    pau     e
2     2435   30450000       e      n     N
3     3040   35800000       N      e     n
4     3575   36200000       n      N     e
5     3615   42200000       e      n     N
6     4215   49800000       N      e     k
7     4975   50850000       k      N     o
8     5080   53800000       o      k     r
9     5375   54650000       r      o     o
10    5460   60150000       o      r     r
11    6010   60650000       r      o     i
12    6060   66650000       i      r     y
13    6660   66900000       y      i     o
14    6685   72550000       o      y   pau
15    7250   75100000     pau      o     o
16    7505   77900000       o    pau     k
17    7785   78600000       k      o     o
18    7855   81800000       o      k     o
19    8175   84350000       o      o     r
20    8430   85000000       r      o     o
21    8495   90400000       o      r     r
22    9035   91150000       r      o     i
23    9110   96400000       i      r     y
24    9635   96650000       y      i     o
25    9660  114400000       o      y   pau
26   11435  119600000     pau      o     b
27   11955  121250000       b    pau     o
28   12120  128450000       o      b     o
29   12840  131750000       o      o     y
..     ...        ...     ...    ...   ...
127  46865  474150000       o      m     r
128  47410  475000000       r      o     o
129  47495  479600000       o      r     t
130  47955  480400000       t      o     a
131  48035  498000000       a      t   pau
132  49795  503600000     pau      a     d
133  50355  505000000       d    pau     e
134  50495  513000000       e      d     N
135  51295  516200000       N      e     d
136  51615  516650000       d      N     e
137  51660  522150000       e      d     N
138  52210  525450000       N      e     N
139  52540  530850000       N      N     d
140  53080  531150000       d      N     a
141  53110  534300000       a      d     i
142  53425  539650000       i      a     k
143  53960  540700000       k      i     o
144  54065  545700000       o      k     n
145  54565  546750000       n      o     i
146  54670  551900000       i      n   pau
147  55185  554450000     pau      i    sh
148  55440  555650000      sh    pau     o
149  55560  558850000       o     sh     o
150  55880  564000000       o      o     n
151  56395  564850000       n      o     o
152  56480  570350000       o      n     f
153  57030  571450000       f      o     u
154  57140  577500000       u      f     e
155  57745  598350000       e      u   pau
156  59830  624000000     pau      e  None

[157 rows x 5 columns]

In [ ]:
# # get one-hot-vector, call phone_to_one_hot() to a specific position
one_hot = phone_to_one_hot(df_list[0]['current'][1])
print(df_list[0]['current'][1], one_hot)